Table Config {
  key String [pk]
  type String
  value String
}

Table User {
  id Int [pk, increment]
  email String [unique]
  name String
  lastName String
  password String
  role String
  active Boolean
  createdAt DateTime
  updatedAt DateTime
}

Table Product {
  id Int [pk, increment]
  name String
  description String
  price Decimal
  image String
  reference String
  createdAt DateTime
  updatedAt DateTime
  active Boolean
}

Table ProductComponent {
  id Int [pk, increment]
  parentProduct Int
  childProduct Int
  quantity Int
  Parent Product [ref: > Product.id]
  Child Product [ref: > Product.id]
}

Table Category {
  id Int [pk, increment]
  name String [unique]
  description String
}

Table ProductCategory {
  id Int [pk, increment]
  product Int
  category Int
  Product Product [ref: > Product.id]
  Category Category [ref: > Category.id]
}

Table StockMovement {
  id Int [pk, increment]
  product Int
  quantity Int
  date DateTime
  user Int
  User User [ref: > User.id]
  Product Product [ref: > Product.id]
}

Table Task {
  id Int [pk, increment]
  worker Int
  createdAt DateTime
  notes String
  User User [ref: > User.id]
}

Table SubTask {
  id Int [pk, increment]
  task Int
  product Int
  quantity Int
  status String
  notes String
  Task Task [ref: > Task.id]
  Product Product [ref: > Product.id]
}

Table SubTaskEvent {
  id Int [pk, increment]
  subtask Int
  date DateTime
  quantityCompleted Int
  SubTask SubTask [ref: > SubTask.id]
}

Table Log {
  id Int [pk, increment]
  tableName String
  rowId Int
  action String
  date DateTime
  user Int
  User User [ref: > User.id]
}

Table session {
  sid String [pk]
  sess String
  expire DateTime
}
