Table Administrator {
  id int [pk, increment]
  email varchar [unique, not null]
  name varchar [not null]
  last_name varchar
  password varchar [not null]
}

Table AdministratorLogs {
  id int [pk, increment]
  administrator int [ref: > Administrator.id]
  action varchar [not null]
  date datetime [not null]
}

Table Worker {
  id int [pk, increment]
  email varchar [unique, not null]
  name varchar [not null]
  last_name varchar
  password varchar [not null]
}

Table WorkerLogs {
  id int [pk, increment]
  worker int [ref: > Worker.id]
  action varchar [not null]
  date datetime [not null]
}

Table Product {
  id int [pk, increment]
  name varchar [not null]
  description text
  price decimal [not null]
  stock int [not null]
  image varchar
  created_at datetime [not null]
  updated_at datetime [not null]
}

Table ProductLogs {
  id int [pk, increment]
  product int [ref: > Product.id]
  action varchar [not null]
  date datetime [not null]
}

Table Category {
  id int [pk, increment]
  name varchar [not null]
  description text
}

Table ProductCategories {
  id int [pk, increment]
  product int [ref: > Product.id]
  category int [ref: > Category.id]
}

Table Stock {
  id int [pk, increment]
  product int [ref: > Product.id]
  quantity int [not null]
  date datetime [not null]
}

Table StockLogs {
  id int [pk, increment]
  stock int [ref: > Stock.id]
  action varchar [not null]
  date datetime [not null]
}

Table ProductionTable {
  id int [pk, increment]
  created_at datetime [not null]
  updated_at datetime [not null]
}

Table ProductionTableLogs {
  id int [pk, increment]
  production_table int [ref: > ProductionTable.id]
  action varchar [not null]
  date datetime [not null]
}


Table Task {
  id int [pk, increment]
  production_table int [ref: > ProductionTable.id]
  worker int [ref: > Worker.id]
  product int [ref: > Product.id]
  quantity int [not null]
  created_at datetime [not null]
  start_time datetime
  end_time datetime
}

Table TaskLogs {
  id int [pk, increment]
  task int [ref: > Task.id]
  action varchar [not null]
  date datetime [not null]
  time datetime
}