get:
  operationId: getConfig
  security:
    - {}
  tags:
    - Config
  summary: Get all configurations
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ConfigResponse.yaml
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '500':
      description: Internal server error
put:
  operationId: updateConfig
  security:
    - {}
  tags:
    - Config
  summary: Update a configuration
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ConfigRequest.yaml
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ConfigResponse.yaml
    '401':
      description: Unauthorized
    '403':
      description: Forbidden
    '500':
      description: Internal server error
