get:
  operationId: getProduction
  security:
    - {}
  tags:
    - Production
  summary: Get all productions
  parameters:
    - name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 25
    - name: page
      in: query
      required: false
      schema:
        type: integer
        default: 1
    - name: userId
      in: query
      required: false
      schema:
        type: integer
    - name: startDate
      in: query
      required: false
      schema:
        type: string
        format: date
    - name: endDate
      in: query
      required: false
      schema:
        type: string
        format: date
    - name: productId
      in: query
      required: false
      schema:
        type: integer
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: ../components/schemas/ProductionResponse.yaml
              nextPage:
                type: integer
                nullable: true
                example: null
              prevPage:
                type: integer
                nullable: true
                example: null
              total:
                type: integer
                example: 1
    '400':
      description: Invalid input
    '500':
      description: Internal server error
