type: object
properties:
  id:
    type: integer
    description: The product's id
    example: 1
  name:
    type: string
    description: The product's name
    example: Product 1
  description:
    type: string
    description: The product's description
    example: Product 1 description
  price:
    type: number
    description: The product's price
    example: 10.99
  reference:
    type: string
    description: The product's reference
    example: REF-001
  createdAt:
    type: string
    format: date-time
    description: The user's creation date
    example: '2021-01-01T00:00:00.000Z'
  updatedAt:
    type: string
    format: date-time
    description: The user's update date
    example: '2021-01-01T00:00:00.000Z'
  categories:
    type: array
    description: The product's categories
    items:
      schema: null
      $ref: ./CategoryResponse.yaml
  active:
    type: boolean
    description: The product's active status
    example: true
    default: true
  components:
    type: array
    description: The product's components
    items:
      type: object
      properties:
        product:
          type: object
          properties:
            id:
              type: integer
              description: The component's product id
              example: 2
            name:
              type: string
              description: The component's product name
              example: Product 2
            description:
              type: string
              description: The component's product description
              example: Product 2 description
            price:
              type: number
              description: The component's product price
              example: 10.99
            reference:
              type: string
              description: The component's product reference
              example: REF-002
            createdAt:
              type: string
              format: date-time
              description: The user's creation date
              example: '2021-01-01T00:00:00.000Z'
            updatedAt:
              type: string
              format: date-time
              description: The user's update date
              example: '2021-01-01T00:00:00.000Z'
        quantity:
          type: integer
          description: The quantity of the component
          example: 3
